default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: no-commit-to-branch
        args: ['--branch=production']
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        additional_dependencies: ['toml']

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ['--target-version=py310']
        additional_dependencies: ['toml']

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      args: [
        '--max-line-length=88',
        '--select=C,E,F,W,B,B950',
        '--extend-ignore=E203,E501'
      ]
